Repository networkit/networkit, pull requests merged in 2022-08, with the labels that each got.

#951 Fix segmentation fault in ParallelConnectedComponents
  CMakeLists.txt
  networkit/cpp/components/ParallelConnectedComponents.cpp
  networkit/cpp/components/test/ConnectedComponentsGTest.cpp
Labels: bug

#974 clang-format sources of overlap, randomization, simulation, and sparsification
  networkit/cpp/overlap/HashingOverlapper.cpp
  networkit/cpp/overlap/test/OverlapGTest.cpp
  networkit/cpp/randomization/GlobalTradeSequence.hpp
  networkit/cpp/simulation/EpidemicSimulationSEIR.cpp
  networkit/cpp/sparsification/ChanceCorrectedTriangleScore.cpp
  networkit/cpp/sparsification/ForestFireScore.cpp
  networkit/cpp/sparsification/LocalDegreeScore.cpp
  networkit/cpp/sparsification/LocalSimilarityScore.cpp
  networkit/cpp/sparsification/MultiscaleScore.cpp
  networkit/cpp/sparsification/RandomEdgeScore.cpp
  networkit/cpp/sparsification/RandomNodeEdgeScore.cpp
  networkit/cpp/sparsification/SCANStructuralSimilarityScore.cpp
  networkit/cpp/sparsification/SimmelianOverlapScore.cpp
  networkit/cpp/sparsification/SimmelianScore.cpp
  networkit/cpp/sparsification/Sparsifiers.cpp
  networkit/cpp/sparsification/test/LocalDegreeGTest.cpp
  networkit/cpp/sparsification/test/LocalSimilarityGTest.cpp
  networkit/cpp/sparsification/test/MultiscaleBackboneGTest.cpp
  networkit/cpp/sparsification/test/SimmelianBackboneGTest.cpp
  networkit/cpp/sparsification/test/SparsificationBenchmark.cpp
Labels: code quality

#981 GHA: Fix errors for notebook tests and activate error output on std.
  .github/workflows/ci.yml
  .github/workflows/scripts/full.sh
  notebooks/test_notebooks.py
Labels: CI

#972 Modify addEdge to check for multi-edges
  include/networkit/graph/Graph.hpp
  networkit/cpp/graph/Graph.cpp
  networkit/cpp/io/DibapGraphReader.cpp
  networkit/cpp/io/GMLGraphReader.cpp
  networkit/cpp/io/GraphToolBinaryReader.cpp
  networkit/cpp/io/KONECTGraphReader.cpp
  networkit/cpp/io/METISGraphReader.cpp
  networkit/cpp/io/NetworkitBinaryReader.cpp
  networkit/graph.pxd
  networkit/graph.pyx
  notebooks/GraphNotebook.ipynb
Labels: new feature

#982 Clang format sources of community
  networkit/cpp/community/AdjustedRandMeasure.cpp
  networkit/cpp/community/ClusteringGenerator.cpp
  networkit/cpp/community/CommunityDetectionAlgorithm.cpp
  networkit/cpp/community/Conductance.cpp
  networkit/cpp/community/CoverF1Similarity.cpp
  networkit/cpp/community/CoverHubDominance.cpp
  networkit/cpp/community/Coverage.cpp
  networkit/cpp/community/CutClustering.cpp
  networkit/cpp/community/DissimilarityMeasure.cpp
  networkit/cpp/community/DynamicNMIDistance.cpp
  networkit/cpp/community/EdgeCut.cpp
  networkit/cpp/community/GraphClusteringTools.cpp
  networkit/cpp/community/GraphStructuralRandMeasure.cpp
  networkit/cpp/community/HubDominance.cpp
  networkit/cpp/community/IntrapartitionDensity.cpp
  networkit/cpp/community/IsolatedInterpartitionConductance.cpp
  networkit/cpp/community/IsolatedInterpartitionExpansion.cpp
  networkit/cpp/community/JaccardMeasure.cpp
  networkit/cpp/community/LPDegreeOrdered.cpp
  networkit/cpp/community/LocalCoverEvaluation.cpp
  networkit/cpp/community/LocalPartitionEvaluation.cpp
  networkit/cpp/community/Modularity.cpp
  networkit/cpp/community/NMIDistance.cpp
  networkit/cpp/community/NodeStructuralRandMeasure.cpp
  networkit/cpp/community/PLM.cpp
  networkit/cpp/community/PLP.cpp
  networkit/cpp/community/ParallelAgglomerativeClusterer.cpp
  networkit/cpp/community/PartitionFragmentation.cpp
  networkit/cpp/community/PartitionHubDominance.cpp
  networkit/cpp/community/PartitionIntersection.cpp
  networkit/cpp/community/SampledGraphStructuralRandMeasure.cpp
  networkit/cpp/community/SampledNodeStructuralRandMeasure.cpp
  networkit/cpp/community/StablePartitionNodes.cpp
  networkit/cpp/community/test/CommunityDetectionBenchmark.cpp
  networkit/cpp/community/test/CommunityGTest.cpp
Labels: code quality

#984 Fix crash of SPSP in case of unreachable targets
  networkit/cpp/distance/MultiTargetBFS.cpp
  networkit/cpp/distance/MultiTargetDijkstra.cpp
  networkit/cpp/distance/test/DistanceGTest.cpp
Labels: bug
