Repository networkit/networkit, pull requests merged in 2022-05, with the labels that each got.

#897 Refactor: components
  include/networkit/components/BiconnectedComponents.hpp
  include/networkit/components/DynConnectedComponents.hpp
  include/networkit/components/DynWeaklyConnectedComponents.hpp
  include/networkit/components/ParallelConnectedComponents.hpp
  networkit/components.pyx
  networkit/cpp/components/BiconnectedComponents.cpp
  networkit/cpp/components/ComponentDecomposition.cpp
  networkit/cpp/components/ConnectedComponentsImpl.cpp
  networkit/cpp/components/ConnectedComponentsImpl.hpp
  networkit/cpp/components/DynConnectedComponents.cpp
  networkit/cpp/components/DynConnectedComponentsImpl.hpp
  networkit/cpp/components/DynWeaklyConnectedComponents.cpp
  networkit/cpp/components/ParallelConnectedComponents.cpp
  networkit/cpp/components/test/ConnectedComponentsGTest.cpp
Labels: bug, performance

#917 Add option to return distances as numpy arrays.
  networkit/centrality.pyx
  networkit/clique.pyx
  networkit/coarsening.pyx
  networkit/community.pyx
  networkit/components.pyx
  networkit/distance.pyx
  networkit/dynamics.pxd
  networkit/embedding.pyx
  networkit/engineering.pyx
  networkit/flow.pyx
  networkit/generators.pyx
  networkit/globals.pyx
  networkit/graph.pxd
  networkit/graphio.pyx
  networkit/graphtools.pyx
  networkit/helpers.pxd
  networkit/helpers.pyx
  networkit/linkprediction.pyx
  networkit/matching.pxd
  networkit/randomization.pyx
  networkit/reachability.pyx
  networkit/scd.pxd
  networkit/simulation.pyx
  networkit/sparsification.pyx
  networkit/stats.pyx
  networkit/structures.pxd
  networkit/test/test_algorithms.py
  networkit/traversal.pyx
  networkit/viz.pyx
Labels: enhancement, performance

#929 Fix #928: Use correct CFF key
  CITATION.cff
Labels: bug

#927 Merge Python module 'exceptions' into 'helpers'
  networkit/exceptions.py
  networkit/helpers.pyx
  networkit/simulation.pyx
Labels: refactor

#926 Python doc: Fix missing/wrong strings for viz-module
  docs/python_api/viz.rst
  docs/python_api/vizbridges.rst
  networkit/viz.pyx
Labels: bug, enhancement

#930 Deprecate Python modules GEXFIO and GraphMLIO
  networkit/GEXFIO.py
  networkit/GraphMLIO.py
  networkit/graphio.pyx
Labels: refactor

#939 GraphEvent: use defaultEdgeWeight as default edge weight
  include/networkit/dynamics/GraphEvent.hpp
Labels: enhancement

#936 Use node iterator to sort nodes by degree
  networkit/cpp/distance/NeighborhoodFunctionHeuristic.cpp
Labels: refactor

#937 clang-format 'algebraic' and 'clique' sources
  networkit/cpp/GlobalState.cpp
  networkit/cpp/Unittests-X.cpp
  networkit/cpp/algebraic/DenseMatrix.cpp
  networkit/cpp/algebraic/DynamicMatrix.cpp
  networkit/cpp/algebraic/Vector.cpp
  networkit/cpp/algebraic/test/AlgebraicBFSGTest.cpp
  networkit/cpp/algebraic/test/AlgebraicBellmanFordGTest.cpp
  networkit/cpp/algebraic/test/AlgebraicMatchingCoarseningGTest.cpp
  networkit/cpp/algebraic/test/AlgebraicPageRankGTest.cpp
  networkit/cpp/algebraic/test/AlgebraicSpanningEdgeCentralityGTest.cpp
  networkit/cpp/algebraic/test/AlgebraicTriangleCountingGTest.cpp
  networkit/cpp/algebraic/test/GraphBLASGTest.cpp
  networkit/cpp/algebraic/test/MatricesGTest.cpp
  networkit/cpp/algebraic/test/VectorGTest.cpp
  networkit/cpp/clique/MaximalCliques.cpp
  networkit/cpp/clique/test/CliqueGTest.cpp
  networkit/cpp/clique/test/MaximalCliquesGTest.cpp
  networkit/cpp/networkit.cpp
Labels: enhancement, refactor

#932 Fix Bug in DynDijstrika related to previously visited nodes.
  networkit/cpp/distance/DynDijkstra.cpp
  networkit/cpp/distance/test/DynSSSPGTest.cpp
Labels: bug

#934 Deprecate Python module 'partitioning'. Move functionality to 'community'.
  include/networkit/community/GraphClusteringTools.hpp
  networkit/community.pyx
  networkit/cpp/community/GraphClusteringTools.cpp
  networkit/partitioning.py
Labels: bug, refactor

#947 Increase timeout for coverage build
  .github/workflows/ci.yml
Labels: CI
