Repository networkit/networkit, pull requests merged in 2022-11, with the labels that each got.

#1001 CI: Raise llvm toolkit to v15.0 (clang, clang-format, clang-tidy)
  .clang-tidy
  .github/workflows/build_wheels.yml
  .github/workflows/ci.yml
  .github/workflows/scripts/clang_tidy.sh
  networkit/cpp/centrality/KadabraBetweenness.cpp
  networkit/cpp/distance/DynBFS.cpp
Labels: CI

#998 Remove possibility to ignore unformatted files
  docs/DevGuide.rst
  extrafiles/tooling/CppClangFormat.py
Labels: removal

#1000 Add support for python 3.11
  .github/workflows/build_wheels.yml
  .github/workflows/ci.yml
Labels: new feature, CI

#1003 SpanningTree: bugfix suggestion and tests
  networkit/cpp/graph/KruskalMSF.cpp
  networkit/cpp/graph/test/SpanningGTest.cpp
Labels: bug

#1006 User-Guide.iypnb: Link IO-notebook, correct degree distribution figure.
  notebooks/User-Guide.ipynb
Labels: doc

#997 Allow single % and integer weights with MatrixMarketReader
  input/GD01_b.mtx
  input/Hamrle1.mtx
  input/LFAT5.mtx
  input/README.md
  input/Ragusa16.mtx
  input/chesapeake.mtx
  networkit/cpp/io/MatrixMarketReader.cpp
  networkit/cpp/io/test/IOGTest.cpp
Labels: bug, code quality

#983 Refactor PLP
  networkit/cpp/community/PLP.cpp
Labels: bug, performance

#1004 Refactor TopCloseness, TopHarmonicCloseness
  CMakeLists.txt
  include/networkit/centrality/TopCloseness.hpp
  include/networkit/centrality/TopHarmonicCloseness.hpp
  networkit/centrality.pyx
  networkit/cpp/centrality/TopCloseness.cpp
  networkit/cpp/centrality/TopHarmonicCloseness.cpp
  networkit/cpp/centrality/test/CMakeLists.txt
  networkit/cpp/centrality/test/CentralityGTest.cpp
  networkit/cpp/centrality/test/TopClosenessGTest.cpp
Labels: performance, new feature
