Repository networkit/networkit, pull requests merged in 2022-12, with the labels that each got.

#1019 Update sklearn -> scikit-learn
  Dockerfile
  requirements.txt
Labels: general

#1009 Fix NetworkitBinaryWriter - writing graphs with deleted nodes
  networkit/cpp/io/NetworkitBinaryWriter.cpp
  networkit/cpp/io/test/IOGTest.cpp
Labels: bug

#1012 New Algorithm: Pruned Landmark Labeling
  include/networkit/distance/PrunedLandmarkLabeling.hpp
  networkit/cpp/distance/CMakeLists.txt
  networkit/cpp/distance/PrunedLandmarkLabeling.cpp
  networkit/cpp/distance/test/DistanceGTest.cpp
  networkit/distance.pyx
  networkit/test/test_distance_algorithms.py
  notebooks/Distance.ipynb
Labels: new feature

#1015 CMakeLists.txt: Add manual homebrew-path for OpenMP detection on macOS arm64
  CMakeLists.txt
Labels: bug

#1022 Documentation: Fixes rendering and typos of "degree distribution" paragraph from User-Guide notebook
  .github/workflows/scripts/documentation.sh
  notebooks/User-Guide.ipynb
Labels: bug

#1021 node2vec: Add checks in order to avoid unexpected behavior and segfaults
  networkit/cpp/embedding/Node2Vec.cpp
  networkit/cpp/embedding/test/FiniteEmbeddingTest.cpp
Labels: bug
