Repository networkit/networkit, pull requests merged in 2023-11, with the labels that each got.

#1141 gtests: adds linkprediction test
  networkit/cpp/linkprediction/test/LinkPredictionGTest.cpp
Labels: code quality

#964 Add option to add edges from a scipy.sparse.coo_matrix and numpy cython support
  .github/workflows/build_wheels.yml
  .github/workflows/ci.yml
  .github/workflows/scripts/core_sanitizers_coverage.sh
  .github/workflows/scripts/full.sh
  CMakeLists.txt
  networkit/__init__.py
  networkit/graph.pyx
  networkit/graphtools.pyx
  networkit/test/test_graph.py
  notebooks/GraphNotebook.ipynb
  pyproject.toml
  requirements.txt
  setup.py
Labels: new feature

#1127 fix: compactEdges
  include/networkit/graph/Graph.hpp
  networkit/cpp/graph/Graph.cpp
  networkit/cpp/graph/test/GraphGTest.cpp
Labels: bug

#1133 Slightly improve the performance of the HyperbolicGenerator
  include/networkit/geometric/HyperbolicSpace.hpp
  networkit/cpp/centrality/test/CentralityGTest.cpp
  networkit/cpp/generators/HyperbolicGenerator.cpp
  networkit/cpp/geometric/HyperbolicSpace.cpp
Labels: performance
