Repository networkit/networkit, pull requests merged in 2023-08, with the labels that each got.

#1092 python test: adds test_structures.py
  networkit/test/test_structures.py
Labels: code quality, CI

#1079 python tests: improves test_centrality
  networkit/test/test_centrality.py
Labels: code quality, CI

#1072 python unit tests: adds more tests for flow, generators and engineering
  networkit/test/test_engineering.py
  networkit/test/test_flow.py
  networkit/test/test_generators.py
Labels: code quality, CI

#1113 CI: Fix maybe-uninitialized warning for gcc 12.3.0
  networkit/cpp/distance/test/SSSPGTest.cpp
Labels: bug, CI

#1108 community.pyx: spectralPartitioner fix
  networkit/community.pyx
Labels: bug

#1115 test_centrality.py: fix groupCloseness test
  networkit/test/test_centrality.py
Labels: CI

#1075 python unit tests: adds test_clique and adds functions in test_community
  networkit/test/test_clique.py
  networkit/test/test_community.py
Labels: code quality, CI
