Repository networkit/networkit, pull requests merged in 2023-10, with the labels that each got.

#1099 fix: plot.py, also adds corresponding jupyter notebook
  .github/workflows/scripts/core_sanitizers_coverage.sh
  docs/notebooks.rst
  include/networkit/graph/Graph.hpp
  networkit/cpp/distance/HopPlotApproximation.cpp
  networkit/graph.pxd
  networkit/graph.pyx
  networkit/plot.py
  notebooks/Plot.ipynb
Labels: bug, code quality

#1135 Fix documentation build error and mark the build as optional for CI.
  .github/workflows/ci.yml
  .github/workflows/scripts/documentation.sh
Labels: bug, doc

#1137 Clang-format creates a new line at the end of the file.
  .clang-format
  networkit/cpp/auxiliary/test/SparseVectorGTest.cpp
  networkit/cpp/centrality/DynApproxBetweenness.cpp
  networkit/cpp/correlation/test/AssortativityGTest.cpp
  networkit/cpp/graph/TopologicalSort.cpp
  networkit/cpp/graph/test/TopologicalSortGTest.cpp
Labels: code-style

#1134 Use string_view instead of const string&.
  include/networkit/auxiliary/StringTools.hpp
Labels: code quality, performance

#1123 gtests: adds centrality tests
  include/networkit/centrality/Sfigality.hpp
  include/networkit/centrality/SpanningEdgeCentrality.hpp
  networkit/cpp/centrality/Sfigality.cpp
  networkit/cpp/centrality/SpanningEdgeCentrality.cpp
  networkit/cpp/centrality/test/CentralityGTest.cpp
Labels: code quality

#1112 graphio: add function to guess file format
  networkit/graphio.pyx
  networkit/test/test_graphio.py
Labels: new feature

#1122 gtests: adds distance tests
  networkit/cpp/distance/test/DistanceGTest.cpp
Labels: code quality

#1140 Use string_view instead of const string&.
  include/networkit/auxiliary/Log.hpp
  include/networkit/auxiliary/StringBuilder.hpp
  networkit/cpp/auxiliary/Log.cpp
Labels: code quality, performance

#1129 gtests: adds dynamics tests
  input/example_write.dgs
  networkit/cpp/dynamics/DGSWriter.cpp
  networkit/cpp/dynamics/test/DynamicsGTest.cpp
Labels: code quality

#1111 Introduce `EdgeAttributes` (C++, Python)
  include/networkit/graph/Graph.hpp
  networkit/cpp/graph/Graph.cpp
  networkit/cpp/graph/test/AttributeGTest.cpp
  networkit/cpp/graph/test/AttributeTest.cpp
  networkit/cpp/graph/test/CMakeLists.txt
  networkit/cpp/graph/test/GraphGTest.cpp
  networkit/graph.pxd
  networkit/graph.pyx
  networkit/test/test_graph.py
  notebooks/GraphNotebook.ipynb
Labels: new feature
