Repository networkit/networkit, pull requests merged in 2023-07, with the labels that each got.

#1089 python test: adds test in test_reachability.py
  networkit/test/test_reachability.py
Labels: code quality, CI

#1071 python unit tests: adds new tests for graph related functions
  networkit/test/test_graph.py
Labels: code quality, CI

#1101 docu: fix wikipedia link
  networkit/community.pyx
Labels: doc

#1058 Graph.hpp: fixes segmenation fault for degree functions
  include/networkit/graph/Graph.hpp
  notebooks/GraphNotebook.ipynb
Labels: code quality

#1074 Unit testing: adds test_algebraic.py and more tests for MatricesGtest.cpp
  networkit/cpp/algebraic/test/MatricesGTest.cpp
  networkit/test/test_algebraic.py
Labels: code quality, CI

#1091 python test: adds tests in test_scd.py
  networkit/test/test_scd.py
Labels: code quality, CI

#1088 python test: adds tests in test_matching.py
  networkit/test/test_matching.py
Labels: code quality, CI

#1096 Fix kCoreCommunityDetection
  networkit/community.pyx
Labels: bug

#1086 python tests: improves test_distance.py
  networkit/test/test_distance.py
Labels: code quality, CI

#1087 python tests: adds test_linkprediction.py
  networkit/test/test_linkprediction.py
Labels: code quality, CI

#1107 pyproject.toml: Add wheel as requirement and pin stable versions of cython, setuptools.
  .github/workflows/build_wheels.yml
  .github/workflows/ci.yml
  .github/workflows/scripts/documentation.sh
  .github/workflows/scripts/full.sh
  pyproject.toml
Labels: general

#1103 Fix clang-tidy errors
  .github/workflows/ci.yml
  .github/workflows/scripts/clang_tidy.sh
  networkit/cpp/centrality/ApproxElectricalCloseness.cpp
  networkit/cpp/centrality/DynBetweenness.cpp
  networkit/cpp/components/StronglyConnectedComponents.cpp
  networkit/cpp/generators/DynamicHyperbolicGenerator.cpp
  networkit/cpp/generators/HavelHakimiGenerator.cpp
  networkit/cpp/generators/HyperbolicGenerator.cpp
  networkit/cpp/generators/MocnikGenerator.cpp
  networkit/cpp/generators/PubWebGenerator.cpp
  networkit/cpp/randomization/CurveballImpl.cpp
  networkit/cpp/sparsification/SimmelianScore.cpp
Labels: bug, code quality

#1102 Refactor Matrices and MatricesGTest
  include/networkit/algebraic/CSRGeneralMatrix.hpp
  include/networkit/algebraic/DenseMatrix.hpp
  include/networkit/algebraic/DynamicMatrix.hpp
  networkit/cpp/Unittests-X.cpp
  networkit/cpp/algebraic/DenseMatrix.cpp
  networkit/cpp/algebraic/test/MatricesGTest.cpp
Labels: code quality
