Repository networkit/networkit, pull requests merged in 2023-06, with the labels that each got.

#1067 Add DynAlgorithm bindings to python
  CMakeLists.txt
  docs/python_api/base.rst
  docs/python_api/dynbase.rst
  docs/python_api/modules.rst
  include/networkit/centrality/DynBetweennessOneNode.hpp
  networkit/base.pxd
  networkit/base.pyx
  networkit/centrality.pyx
  networkit/components.pyx
  networkit/distance.pyx
  networkit/dynbase.pxd
  networkit/dynbase.pyx
  networkit/reachability.pyx
Labels: code quality, new feature

#1078 distance.pyx: repairs jaccardDistance
  networkit/distance.pyx
Labels: bug

#1060 CommunityGTest.cpp: adds testCoverHubDominance
  networkit/cpp/community/test/CommunityGTest.cpp
Labels: code quality

#1064 Fix #1063: BiconnectedComponents bug
  networkit/cpp/components/BiconnectedComponents.cpp
  networkit/cpp/components/test/BiconnectedComponentsGTest.cpp
Labels: bug

#1073 Documentation: adds reminder for users in graphDegree functions
  include/networkit/graph/Graph.hpp
  networkit/graph.pyx
Labels: doc

#1095 python test: adds test in test_independentset.py
  networkit/test/test_independentset.py
Labels: code quality, CI

#1085 python tests: adds more tests into test_component.py
  networkit/test/test_component.py
Labels: code quality, CI
