Repository networkit/networkit, pull requests merged in 2024-07, with the labels that each got.

#1232 python: fix addEdge when adding missing nodes
  networkit/graph.pyx
  networkit/test/test_graph.py
Labels: bug, general

#1235 graph.pyx: adjust datatypes to be compatible with numpy2.0
  .github/workflows/ci.yml
  README.md
  networkit/graph.pyx
  pyproject.toml
Labels: CI

#1212 Lamg: parallel solve for multiple components
  include/networkit/numerics/ConjugateGradient.hpp
  include/networkit/numerics/LAMG/Lamg.hpp
  include/networkit/numerics/LAMG/SolverLamg.hpp
  include/networkit/numerics/LinearSolver.hpp
  networkit/cpp/numerics/CMakeLists.txt
  networkit/cpp/numerics/Lamg.cpp
  networkit/cpp/numerics/test/CMakeLists.txt
  networkit/cpp/numerics/test/LAMGGTest.cpp
  networkit/cpp/numerics/test/SolverLamgGTest.cpp
  networkit/cpp/viz/test/CMakeLists.txt
Labels: bug, performance, new feature

#1177 adds chungLuAlamEtAl generator + tests
  include/networkit/generators/ChungLuGeneratorAlamEtAl.hpp
  networkit/cpp/generators/CMakeLists.txt
  networkit/cpp/generators/ChungLuGeneratorAlamEtAl.cpp
  networkit/cpp/generators/test/GeneratorsGTest.cpp
Labels: code quality
