Repository networkit/networkit, pull requests merged in 2024-06, with the labels that each got.

#1194 introduces new parallel graph builder and deprecates old one
  include/networkit/graph/GraphBuilder.hpp
  networkit/cpp/generators/ChungLuGenerator.cpp
  networkit/cpp/generators/ClusteredRandomGraphGenerator.cpp
  networkit/cpp/generators/ErdosRenyiGenerator.cpp
  networkit/cpp/generators/HyperbolicGenerator.cpp
  networkit/cpp/graph/GraphBuilder.cpp
  networkit/cpp/graph/test/GraphBuilderAutoCompleteGTest.cpp
  networkit/cpp/io/ThrillGraphBinaryReader.cpp
  networkit/cpp/sparsification/GlobalThresholdFilter.cpp
  networkit/test/test_graphio.py
Labels: performance

#1229 python: fix overlapping_nmi_distance + add test
  networkit/community.pyx
  networkit/test/test_community.py
Labels: bug

#1228 c++: adds usability related matrix operators and tests
  include/networkit/algebraic/CSRGeneralMatrix.hpp
  include/networkit/algebraic/DenseMatrix.hpp
  include/networkit/algebraic/DynamicMatrix.hpp
  include/networkit/algebraic/MatrixTools.hpp
  networkit/cpp/algebraic/DenseMatrix.cpp
  networkit/cpp/algebraic/DynamicMatrix.cpp
  networkit/cpp/algebraic/test/MatricesGTest.cpp
Labels: code quality, new feature

#1210 Improve LAMG helper classes
  include/networkit/numerics/LAMG/Lamg.hpp
  include/networkit/numerics/LAMG/LevelHierarchy.hpp
  include/networkit/numerics/LAMG/MultiLevelSetup.hpp
  include/networkit/numerics/LAMG/SolverLamg.hpp
  networkit/cpp/algebraic/test/CMakeLists.txt
  networkit/cpp/centrality/test/CMakeLists.txt
  networkit/cpp/distance/test/CMakeLists.txt
  networkit/cpp/numerics/CMakeLists.txt
  networkit/cpp/numerics/LevelHierarchy.cpp
  networkit/cpp/numerics/MultiLevelSetup.cpp
  networkit/cpp/numerics/SolverLamg.cpp
  networkit/cpp/viz/CMakeLists.txt
Labels: performance, code-style

#1230 vizbridges: adds edge attribute visualization
  networkit/vizbridges.py
  notebooks/Visualization.ipynb
Labels: new feature
