Repository networkit/networkit, pull requests merged in 2024-09, with the labels that each got.

#1252 fix DynamicMatrix * DynamicMatrix
  networkit/cpp/algebraic/DynamicMatrix.cpp
  networkit/cpp/algebraic/test/MatricesGTest.cpp
Labels: bug

#1245 cpp: fixDynBetweennessOneNode for weighted graphs
  include/networkit/centrality/DynBetweennessOneNode.hpp
  networkit/cpp/centrality/DynBetweennessOneNode.cpp
  networkit/cpp/centrality/test/DynBetweennessGTest.cpp
Labels: code quality, new feature

#1254 cython: change ordering of function signatures (nogil)
  networkit/base.pxd
  networkit/community.pyx
  networkit/components.pyx
  networkit/distance.pyx
  networkit/dynamics.pyx
  networkit/dynbase.pxd
  networkit/generators.pyx
  networkit/globals.pyx
  networkit/graph.pxd
  networkit/graphio.pyx
  networkit/graphtools.pyx
  networkit/randomization.pyx
  networkit/traversal.pyx
  networkit/viz.pyx
Labels: code-style

#1251 Fix copy operations for attributes
  include/networkit/graph/Attributes.hpp
  include/networkit/graph/Graph.hpp
  networkit/cpp/graph/Graph.cpp
  networkit/cpp/graph/GraphTools.cpp
  networkit/cpp/graph/test/AttributeGTest.cpp
  networkit/test/test_graph.py
Labels: bug, code quality
