Repository networkit/networkit, pull requests merged in 2024-05, with the labels that each got.

#1215 Fix GTest: make algebraicDistanceGTest deterministic
  networkit/cpp/distance/test/DistanceGTest.cpp
Labels: bug, CI

#1214 add matrix and vector print functions
  include/networkit/algebraic/CSRGeneralMatrix.hpp
  include/networkit/algebraic/DenseMatrix.hpp
  include/networkit/algebraic/DynamicMatrix.hpp
  include/networkit/algebraic/Vector.hpp
  networkit/cpp/algebraic/test/MatricesGTest.cpp
  networkit/cpp/algebraic/test/VectorGTest.cpp
Labels: new feature

#1185 fix: LouvainMapGTest
  networkit/cpp/community/test/LouvainMapEquationGTest.cpp
Labels: CI

#1179 improves rmat generator + adds tests
  include/networkit/generators/RmatGenerator.hpp
  networkit/cpp/generators/RmatGenerator.cpp
  networkit/cpp/generators/test/GeneratorsGTest.cpp
Labels: code quality

#1225 CI: Change Ubuntu image for gcc-13, switch clang-format t 17.X
  .github/workflows/ci.yml
  include/networkit/auxiliary/IncrementalUniformRandomSelector.hpp
  include/networkit/generators/ErdosRenyiEnumerator.hpp
  include/networkit/graph/Graph.hpp
  include/networkit/graph/RandomMaximumSpanningForest.hpp
  include/networkit/graph/UnionMaximumSpanningForest.hpp
  include/networkit/io/NetworkitBinaryReader.hpp
  include/networkit/layout/LayoutAlgorithm.hpp
  include/networkit/structures/LocalCommunity.hpp
  networkit/cpp/centrality/GroupClosenessGrowShrink.cpp
  networkit/cpp/distance/NeighborhoodFunctionHeuristic.cpp
  networkit/cpp/edgescores/PrefixJaccardScore.cpp
  networkit/cpp/generators/test/GeneratorsGTest.cpp
  networkit/cpp/geometric/test/GeometricGTest.cpp
  networkit/cpp/io/test/IOBenchmark.cpp
  networkit/cpp/scd/LocalDegreeDirectedGraph.hpp
  networkit/cpp/scd/LocalTightnessExpansion.cpp
  networkit/cpp/viz/MaxentStress.cpp
  networkit/cpp/viz/test/VizGTest.cpp
Labels: CI

#1220 fix string attribute read
  include/networkit/graph/Graph.hpp
  networkit/cpp/graph/test/AttributeGTest.cpp
Labels: bug
