Repository networkit/networkit, pull requests merged in 2024-01, with the labels that each got.

#1156 add python bindings for attribute read/write
  networkit/graph.pxd
  networkit/graph.pyx
  networkit/test/test_graph.py
Labels: new feature

#1155 Remove previous deprecations for release 11.0.
  CHANGES.md
  docs/python_api/GEXFIO.rst
  docs/python_api/GraphMLIO.rst
  docs/python_api/csbridge.rst
  docs/python_api/partitioning.rst
  docs/python_api/sampling.rst
  docs/python_api/stopwatch.rst
  docs/python_api/viztasks.rst
  docs/python_api/workflows.rst
  include/networkit/components/ParallelConnectedComponents.hpp
  include/networkit/distance/BidirectionalBFS.hpp
  include/networkit/dynamics/GraphEvent.hpp
  include/networkit/graph/GraphBuilder.hpp
  include/networkit/graph/Sampling.hpp
  include/networkit/sparsification/SimmelianScore.hpp
  networkit/GEXFIO.py
  networkit/GraphMLIO.py
  networkit/__init__.py
  networkit/community.pyx
  networkit/cpp/components/ParallelConnectedComponents.cpp
  networkit/cpp/components/test/ConnectedComponentsGTest.cpp
  networkit/cpp/dynamics/GraphEvent.cpp
  networkit/cpp/dynamics/GraphEventProxy.cpp
  networkit/cpp/graph/GraphBuilder.cpp
  networkit/cpp/sparsification/SimmelianScore.cpp
  networkit/csbridge.py
  networkit/distance.pyx
  networkit/dynamic.py
  networkit/engineering.pyx
  networkit/globals.pyx
  networkit/graphtools.pyx
  networkit/helpers.pyx
  networkit/partitioning.py
  networkit/profiling/profiling.py
  networkit/sampling.py
  networkit/stopwatch.py
  networkit/test/test_global.py
  networkit/test/test_graphio.py
  networkit/viztasks.py
  networkit/workflows.py
  notebooks/Distance.ipynb
  notebooks/User-Guide.ipynb
Labels: code quality

#1158 restore_removeEdge_api
  include/networkit/graph/Graph.hpp
  networkit/cpp/graph/Graph.cpp
  networkit/cpp/graph/test/GraphGTest.cpp
Labels: code quality, code-style

#1114 Complex paths
  include/networkit/centrality/ComplexPaths.hpp
  networkit/centrality.pyx
  networkit/cpp/centrality/CMakeLists.txt
  networkit/cpp/centrality/ComplexPaths.cpp
  networkit/cpp/centrality/test/CentralityGTest.cpp
  networkit/test/test_centrality.py
Labels: new feature

#1157 Fix: networkit binary format explanation and update guess format
  include/networkit/io/NetworkitBinaryReader.hpp
  include/networkit/io/NetworkitBinaryWriter.hpp
  input/README.md
  input/foodweb-baydry.nkbg002
  input/foodweb-baydry.nkbg003
  networkit/cpp/io/NetworkitBinaryGraph.md
  networkit/graphio.pyx
  networkit/test/test_graphio.py
  notebooks/IONotebook.ipynb
Labels: doc

#1169 cpp: make lubys algorithm deterministic
  include/networkit/independentset/Luby.hpp
  networkit/cpp/independentset/Luby.cpp
  networkit/cpp/independentset/test/IndependentSetGTest.cpp
Labels: code quality
