Repository networkit/networkit, pull requests merged in 2025-02, with the labels that each got.

#1276 Add Left-Right Planarity Test Algorithm to NetworKit
  include/networkit/graph/Graph.hpp
  include/networkit/planarity/LeftRightPlanarityCheck.hpp
  networkit/cpp/CMakeLists.txt
  networkit/cpp/graph/test/GraphGTest.cpp
  networkit/cpp/planarity/CMakeLists.txt
  networkit/cpp/planarity/LeftRightPlanarityCheck.cpp
  networkit/cpp/planarity/test/CMakeLists.txt
  networkit/cpp/planarity/test/LeftRightPlanarityCheckGTest.cpp
Labels: new feature

#1283 CI: Split coverage and leak build, fix leaks, remove aarch64 wheel build
  .github/workflows/build_wheels.yml
  .github/workflows/ci.yml
  .github/workflows/scripts/coverage.sh
  UBSAN.filter
  include/networkit/community/LouvainMapEquation.hpp
  include/networkit/graph/GraphTools.hpp
  include/networkit/graph/TopologicalSort.hpp
  networkit/cpp/centrality/test/CentralityGTest.cpp
  networkit/cpp/community/LouvainMapEquation.cpp
  networkit/cpp/generators/ChungLuGeneratorAlamEtAl.cpp
  networkit/cpp/graph/GraphTools.cpp
  networkit/cpp/graph/TopologicalSort.cpp
Labels: bug, code quality, CI

#1300 Remove compiler detection from setup.py.
  setup.py
Labels: code quality

#1305 Remove networkit header from gitignore.
  .gitignore
Labels: general

#1296 Issue #938: suppress warning for pandas in networkit/simulation.pyx
  networkit/simulation.pyx
Labels: code quality

#1302 CI: Update Python 3.12 -> 3.13.
  .github/workflows/build_wheels.yml
  .github/workflows/ci.yml
Labels: CI

#1264 Add RB Matrix and Graph reader
  include/networkit/io/RBGraphReader.hpp
  include/networkit/io/RBMatrixReader.hpp
  input/tiny_05.matrixmarket
  input/tiny_05.rb
  networkit/cpp/io/CMakeLists.txt
  networkit/cpp/io/RBGraphReader.cpp
  networkit/cpp/io/RBMatrixReader.cpp
  networkit/cpp/io/test/IOGTest.cpp
  networkit/graphio.pyx
  networkit/test/test_graphio.py
Labels: new feature

#1299 fix edge attribute indexing bugs when changing edge ids
  include/networkit/graph/Attributes.hpp
  networkit/cpp/graph/Graph.cpp
  networkit/cpp/graph/test/AttributeGTest.cpp
Labels: bug

#1301 fix signal handler
  include/networkit/auxiliary/SignalHandling.hpp
  networkit/cpp/auxiliary/SignalHandling.cpp
Labels: bug
